---
- hosts: all
  remote_user: root
  tasks:
   - name: create user "{{username}}"
     user: group=wheel  password={{'123456'|password_hash('sha512')}} name={{username}}
   - shell: chage -d 0 {{username}}
