---
- hosts: cache
  remote_user: root
  vars:
    username: "li5"
  tasks:
    - user:
        name: "{{username}}"
        group: users
        password: "{{'123456'|password_hash('sha512')}}"
    - shell: chage -d 0 "{{username}}"
