#!/bin/bash
yum install libguestfs libguestfs-tools -y &>/dev/null
function set_ip(){
vmname=$1
ip=$2
hostname=$3
mkdir /mnt/$vmname
guestmount -a /var/lib/libvirt/images/$vmname.img -i  --rw /mnt/$vmname
echo $hostname >/mnt/$vmname/etc/hostname
cat > /mnt/$vmname/etc/sysconfig/network-scripts/ifcfg-eth0 <<EOF
# Generated by dracut initrd
NAME="eth0"
DEVICE="eth0"
ONBOOT="yes"
NETBOOT="yes"
IPV6INIT="no"
BOOTPROTO="none"
TYPE="Ethernet"
IPV4_FAILURE_FATAL="no"
IPADDR=$ip
PREFIX=24
GATEWAY=192.168.4.254
EOF
cat >>/mnt/$vmname/etc/hosts <<EOF
192.168.4.1	client
192.168.4.2	node1
192.168.4.3	node2
192.168.4.4	node3
192.168.4.5	node4
192.168.4.6	node5
EOF

#配置yum源
rm -rf /mnt/$vmname/etc/yum.repos.d/*
cp ./dvd.repo /mnt/$vmname/etc/yum.repos.d/dvd.repo

umount /mnt/$vmname
rm -rf /mnt/$vmname
sleep 5
echo "$vmname 主机名和ip地址修改成功！"
}
