---
- hosts: web
  remote_user: root
  tasks:
    - name: install the latest version of Apache
      yum:
        name: httpd
    - copy:
       src: /root/yml/httpd.conf
       dest: /etc/httpd/conf/httpd.conf
       owner: root
       group: root
       mode: 0644
      notify:
        - restart_httpd
    - copy:
       src: /root/yml/index.html
       dest: /var/www/html/index.html
       owner: root
       group: root
       mode: 0644
  handlers:
    - name: restart_httpd
      service: 
        name: httpd
        state: restarted
        enabled: yes

