---
- hosts: cache
  remote_user: root
  vars:
    username: "lili"
  tasks:
   - name: create user "{{username}}"
     user: 
       name: "{{username}}" 
       group: users 
       password: "{{'123456'|password_hash('sha512')}}"
   - shell: chage -d 0 "{{username}}"
