---
- hosts: all
  remote_user: root
  vars_files:
    - vars.yml
  tasks:
   - shell: id "{{user}}"
     register: result
   - shell: adduser "{{user}}"
     ignore_errors: True
   - shell: echo "{{pass}}"|passwd --stdin "{{user}}"
     when: result
   - name: chage
     shell: chage -d 0 "{{user}}"
