---
- hosts: web1
  remote_user: root
  vars_files:
    - vars.yml
  tasks:
   - shell: adduser "{{user}}"
     ignore_errors: True
   - shell: echo "{{pass}}"|passwd --stdin "{{user}}"
   - name: chage
     shell: chage -d 0 "{{user}}"
